# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = ~/EchoTherm-Daemon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = ~/EchoTherm-Daemon

CURRENT_DIR := $(notdir $(shell pwd))
ifeq ($(CURRENT_DIR),EchoTherm-Daemon)
    $(info Building in correct directory: $(CURRENT_DIR))
else
    $(error Error: Must run make from EchoTherm-Daemon directory. Current directory: $(CURRENT_DIR))
endif

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start ~/EchoTherm-Daemon/CMakeFiles ~/EchoTherm-Daemon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start ~/EchoTherm-Daemon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named echotherm

# Build rule for target.
echotherm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echotherm
.PHONY : echotherm

# fast build rule for target.
echotherm/fast:
	$(MAKE) -f CMakeFiles/echotherm.dir/build.make CMakeFiles/echotherm.dir/build
.PHONY : echotherm/fast

#=============================================================================
# Target rules for targets named echothermd

# Build rule for target.
echothermd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echothermd
.PHONY : echothermd

# fast build rule for target.
echothermd/fast:
	$(MAKE) -f CMakeFiles/echothermd.dir/build.make CMakeFiles/echothermd.dir/build
.PHONY : echothermd/fast

src/EchoThermCamera.o: src/EchoThermCamera.cpp.o

.PHONY : src/EchoThermCamera.o

# target to build an object file
src/EchoThermCamera.cpp.o:
	$(MAKE) -f CMakeFiles/echothermd.dir/build.make CMakeFiles/echothermd.dir/src/EchoThermCamera.cpp.o
.PHONY : src/EchoThermCamera.cpp.o

src/EchoThermCamera.i: src/EchoThermCamera.cpp.i

.PHONY : src/EchoThermCamera.i

# target to preprocess a source file
src/EchoThermCamera.cpp.i:
	$(MAKE) -f CMakeFiles/echothermd.dir/build.make CMakeFiles/echothermd.dir/src/EchoThermCamera.cpp.i
.PHONY : src/EchoThermCamera.cpp.i

src/EchoThermCamera.s: src/EchoThermCamera.cpp.s

.PHONY : src/EchoThermCamera.s

# target to generate assembly for a file
src/EchoThermCamera.cpp.s:
	$(MAKE) -f CMakeFiles/echothermd.dir/build.make CMakeFiles/echothermd.dir/src/EchoThermCamera.cpp.s
.PHONY : src/EchoThermCamera.cpp.s

src/echotherm.o: src/echotherm.cpp.o

.PHONY : src/echotherm.o

# target to build an object file
src/echotherm.cpp.o:
	$(MAKE) -f CMakeFiles/echotherm.dir/build.make CMakeFiles/echotherm.dir/src/echotherm.cpp.o
.PHONY : src/echotherm.cpp.o

src/echotherm.i: src/echotherm.cpp.i

.PHONY : src/echotherm.i

# target to preprocess a source file
src/echotherm.cpp.i:
	$(MAKE) -f CMakeFiles/echotherm.dir/build.make CMakeFiles/echotherm.dir/src/echotherm.cpp.i
.PHONY : src/echotherm.cpp.i

src/echotherm.s: src/echotherm.cpp.s

.PHONY : src/echotherm.s

# target to generate assembly for a file
src/echotherm.cpp.s:
	$(MAKE) -f CMakeFiles/echotherm.dir/build.make CMakeFiles/echotherm.dir/src/echotherm.cpp.s
.PHONY : src/echotherm.cpp.s

src/echothermd.o: src/echothermd.cpp.o

.PHONY : src/echothermd.o

# target to build an object file
src/echothermd.cpp.o:
	$(MAKE) -f CMakeFiles/echothermd.dir/build.make CMakeFiles/echothermd.dir/src/echothermd.cpp.o
.PHONY : src/echothermd.cpp.o

src/echothermd.i: src/echothermd.cpp.i

.PHONY : src/echothermd.i

# target to preprocess a source file
src/echothermd.cpp.i:
	$(MAKE) -f CMakeFiles/echothermd.dir/build.make CMakeFiles/echothermd.dir/src/echothermd.cpp.i
.PHONY : src/echothermd.cpp.i

src/echothermd.s: src/echothermd.cpp.s

.PHONY : src/echothermd.s

# target to generate assembly for a file
src/echothermd.cpp.s:
	$(MAKE) -f CMakeFiles/echothermd.dir/build.make CMakeFiles/echothermd.dir/src/echothermd.cpp.s
.PHONY : src/echothermd.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... echotherm"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... echothermd"
	@echo "... src/EchoThermCamera.o"
	@echo "... src/EchoThermCamera.i"
	@echo "... src/EchoThermCamera.s"
	@echo "... src/echotherm.o"
	@echo "... src/echotherm.i"
	@echo "... src/echotherm.s"
	@echo "... src/echothermd.o"
	@echo "... src/echothermd.i"
	@echo "... src/echothermd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

